/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Contact: typeof import('./src/components/contact/Contact.vue')['default']
    Home: typeof import('./src/components/home/Home.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    Personal: typeof import('./src/components/personal/Personal.vue')['default']
    Projects: typeof import('./src/components/projects/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/skill/Skills.vue')['default']
  }
}
